[workspace]
members = [
    "cli",
    "config",
    "core",
    "logger",
    "ledger",
    "model",
    "network",
    "validator"
]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
multiaddr = "0.17.0"
tokio = "1.22.0"
serde = "1.0"

