[package]
name = "mundis-config"
version.workspace = true
edition = "2021"

[dependencies]
serde = { version = "1.0.144", features = ["derive", "rc"] }
multiaddr.workspace = true
thiserror = "1.0"

mundis-model = { path = "../model" }
